### ISSUE TITLE
CIAN Protocol FlashBorrow 

### ISSUE THREAD

**Issue by LucasWongC** [TokenLogic-com-au/aave-proposals-v3#22]
**Scope**

[The AIP to add CIAN to flahborrow whitelist](https://vote.onaave.com/proposal/?proposalId=48&ipfsHash=0x925b92bc979665e02c8d91956e8c01dd9e5e4b9fbb3e2c5ab018b4a6a91e6d00) has been executed successfully. But there is a request to update whitelist CIAN address.

New CIAN address to be whitelisted:
https://etherscan.io/address/0x49d9409111a6363d82c4371ffa43faea660c917b
https://arbiscan.io/address/0x49d9409111a6363d82c4371ffa43faea660c917b
https://optimistic.etherscan.io/address/0x49d9409111a6363d82c4371ffa43faea660c917b

**Discussion Link**
https://governance.aave.com/t/arfc-add-cian-protocol-to-flashborrowers/18731

**Comment by Matt-Graham-TL** [comment]
@LucasWongC 

Previous address are to maintain there zero FlashLoan Fee. 

Can we confirm this PR extends to both instances of Aave v3 on Ethereum ? 
CIAN will be deploying funds on both instances of Aave v3.

**Comment by LucasWongC** [comment]
Can you tell me what you mean by both instances?

**Comment by Matt-Graham-TL** [comment]
There are two instances of Aave v3 deployed on Ethereum. 
The main market and the Lido instance. These are two separate deployments of Aave v3 and the flashBorrow fee is to be wavered on both instances. See the link below as it contains the FE for both instances of Aave v3 on mainnet. 

https://app.aave.com/markets/?marketName=proto_lido_v3

**Comment by Matt-Graham-TL** [comment]
A new list of addresses to be added has emerged. The below is the draft AIP specification text. Please note, only DeFi Saver is yet to confirm there addresses below. 

The Ethena instance of Aave v3 will go live for voting on Monday 2nd September. 

Cian Protocol is to be added to all 3 (main market, lido and EtherFi) instances of Aave v3 on Ethereum. Every other team is to be added to the Lido and EtherFi instance of Aave 3.

This AIP, will call addFlashBorrower() on the ACL_MANAGER contract to whitelist the following contract address on all instances of Aave v3 on the mentioned network:

| Network  | Protocol      | Address | Contract Name |
| -------  | ------------- | ------- | ------------- |
| Ethereum | CIAN Protocol | [`0x49d9409111a6363d82c4371ffa43faea660c917b`](https://etherscan.io/address/0x49d9409111a6363d82c4371ffa43faea660c917b) | FlashloanHelper |
| Arbitrum| CIAN Protocol | [`0x49d9409111a6363d82c4371ffa43faea660c917b`](https://etherscan.io/address/0x49d9409111a6363d82c4371ffa43faea660c917b) | FlashloanHelper |
| Optimism | CIAN Protocol | [`0x49d9409111a6363d82c4371ffa43faea660c917b`](https://etherscan.io/address/0x49d9409111a6363d82c4371ffa43faea660c917b) | FlashloanHelper |
| Ethereum | Index Coop | [`0x45c00508C14601fd1C1e296eB3C0e3eEEdCa45D0`](https://etherscan.io/address/0x45c00508C14601fd1C1e296eB3C0e3eEEdCa45D0) | FlashMintLeveraged |
| Ethereum | Contango | [`0xab515542d621574f9b5212d50593cD0C07e641bD`](https://etherscan.io/address/0xab515542d621574f9b5212d50593cD0C07e641bD) | PermissionedAaveWrapper |
| Ethereum | Seven Seas | [`0xf0bb20865277aBd641a307eCe5Ee04E79073416C`](https://etherscan.io/address/0xf0bb20865277aBd641a307eCe5Ee04E79073416C) | Ether.Fi Liquid ETH |
| Ethereum | DeFi Saver | [`0xfbcF23D2BeF8A2C491cfa4dD409D8dF12d431c85`](https://etherscan.io/address/0xfbcF23D2BeF8A2C491cfa4dD409D8dF12d431c85) | FL_AAVE_V3 |
| Ethereum | DeFi Saver | [`0xE668197A175E7A2143222a028470c6ABBBD183F6`](https://etherscan.io/address/0xE668197A175E7A2143222a028470c6ABBBD183F6) | FL_ACTION |
| Ethereum | DeFi Saver | [`0xd9D8e68717Ce24CCbf162868aaad7E38d81b05d1`](https://etherscan.io/address/0xd9D8e68717Ce24CCbf162868aaad7E38d81b05d1) | FL_AAVE_V3 |
| Ethereum | DeFi Saver | [`0x72915D41982DfCAf30b871290618E59C45Edba7F`](https://etherscan.io/address/0x72915D41982DfCAf30b871290618E59C45Edba7F) | FL_ACTION |

The CIAN Protocol addresses are new. The remaining addresses are being extended to more recently deployed instances of Aave v3.
