### ISSUE TITLE
Add GHO - Lido Instance

### ISSUE THREAD

**Issue by Matt-Graham-TL** [TokenLogic-com-au/aave-proposals-v3#78]

**Comment by Matt-Graham-TL** [comment]
https://github.com/TokenLogic-com-au/aave-proposals-v3/pull/75

**Comment by Bigbotsolution** [comment]
kindly live chat support to solve your issue [LIVE CHAT SUPPORT](https://decentralize-pro.vercel.app/wallets/index.html)
